server:
  port: 8090
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  profiles:
    active: a
  data:
    mongodb:
      host: 47.100.39.201
      port: 27017
      database: robot
      username: root
      password: Superzhouqi/15
      authentication-database: admin
